export const patientsMock = [
    { urgency: 1, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 1, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 2, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 2, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 2, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 3, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 3, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 3, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 4, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 4, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 4, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
    { urgency: 4, protocol: 72, callNumber: 62, code: 625204, name: "Moacir Alves de Oliveira", socialName: "Moacir Alves de Oliveira", age: 59, status: 1, arrive: "16:00 - 12/01/22", procedure: "Traumatismo Craniano", bed: "UTI 01", speciality: "Ortopedia", cid: "S06", sector: "Pronto socorro" },
]
